name: ReaPack

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Pandoc
        run: sudo apt-get install -yy pandoc

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install reapack-index
        run: gem install reapack-index

      - name: Generate ReaPack index
        run: reapack-index --name "arilia ReaScripts" --commit  
      
      - name: Upload index
        uses: actions/upload-artifact@v4
        with:
          name: reapack-index
          path: index.xml
